name: CI/CD

on:
  push:
    branches:
      - dev

env:
  PROJECT_NAME: my-project
  BUCKET_NAME: my-s3-bucket

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Java JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
    
        
      # 빌드
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      
      - name: Build with Gradle
        run: ./gradlew build
